import Head from "next/head";
import Navbar from "../../components/Navbar";
import ContentList from "../../components/ContentList";
import Rightbar from "../../components/Rightbar";

export default function Home({ posts }) {
  return (
    <div className="max-w-screen-2xl w-full h-screen flex mx-auto justify-between pr-4">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
      <div>
        <ContentList posts={posts} />
      </div>
      <div>
        <Rightbar />
      </div>
    </div>
  );
}

export async function getServerSideProps(r,s) {
  const req = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/post/allposts`);
  const allPost = await req.json();
  return {
    props: {
      posts: allPost.result || {},
    },
  };
}
