import Head from "next/head";
import ContentList from "../components/ContentList";
import Rightbar from "../components/Rightbar";

export default function Home() {
  return (
    <div className="max-w-screen-2xl w-full h-screen flex mx-auto justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        <ContentList />
      </div>
      <div>
        <Rightbar />
      </div>
    </div>
  );
}
