import Head from 'next/head'
import Navbar from '../components/Navbar'
import Upload from '../components/Upload'
import Rightbar from '../components/Rightbar'

export default function Home() {
  return (
    <div className='max-w-screen-2xl w-screen h-screen flex mx-auto justify-between'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div><Navbar/></div>
      <div className='w-full'><Upload/></div>
      <div><Rightbar/></div>

    </div>
  )
}
